# Docker compose file để dễ dàng khởi động PostgreSQL và các service khác
services:
  postgres:
    image: postgres:15-alpine
    container_name: file_storage_postgres
    ports:
      - "9010:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file_storage
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    # networks:
    #   - app-network

volumes:
  postgres_data:
