# Docker compose file để dễ dàng khởi động PostgreSQL và các service khác
services:
  postgres:
    image: postgres:15-alpine
    container_name: file_storage_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file_storage
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    # networks:
    #   - app-network

  # # Bạn có thể thêm pgAdmin hoặc các service khác ở đây nếu cần
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: file_storage_pgadmin
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5050:80"
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   restart: always
  #   networks:
  #     - app-network

volumes:
  postgres_data:

# networks:
#   app-network:
#     driver: bridge
